// <auto-generated />
namespace mytinycollege.Migrations.CollegeMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Instructorfix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Instructorfix));
        
        string IMigrationMetadata.Id
        {
            get { return "201605021426467_Instructor(fix)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
